name: release
run-name: Creating releases/${{ inputs.version }}

on:
    workflow_dispatch:
      inputs:
        version:
          description: 'Version'
          required: true
          type: string

jobs:
  create_release_branch:
    name: Create release branch
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Update version
        run: |
          echo -n "${{ github.event.inputs.version }}" > version.txt
          sed -i 's/version = [^;]*/version = ${{ github.event.inputs.version }}/g' setup.cfg
      - name: Create release branch
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git checkout -B releases/${{ github.event.inputs.version }}
          git commit --allow-empty -am "Create version ${{ github.event.inputs.version }}"
          git push --set-upstream origin releases/${{ github.event.inputs.version }}
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-python@v5
      with:
        python-version: 3.11
    - name: Install dependencies
      run: |
          python -m pip install --upgrade pip
          pip install tox tox-gh-actions
    - name: Test with tox
      run: tox

  pypi-publish:
    runs-on: ubuntu-latest
    name: Upload release to PyPI
    environment:
      name: pypi
      url: https://pypi.org/p/python-linkplay
    permissions:
      id-token: write
    steps: 
      - uses: pypa/gh-action-pypi-publish@release/v1